server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:    config:      server:        git:
          uri: https://github.com/kimmurielO/Server-Config-Repository
          default-label: main
          search-paths:
          - '*service'
          